### ISSUE TITLE
Are there any plans for Choices, SegmentedControl, Date Inputs

### ISSUE THREAD

**Issue by akashkamboj** [bpoplauschi/BPForms#24]
Love your library. very easy to implement. Want to use this in a real project.

But one thing is seriously missing from this lib. not all input types are text fields. have to have Choices, SegmentedControl, Date Inputs controls.

I mainly needed Choices which can show UIActionSheet to choose the options.

Do you have any plans for these in near future.

**Comment by bpoplauschi** [comment]
@fpillet Sorry about that, I were just busy. I will refresh that PR of your's. Your contribution is much appreciated.
