### ISSUE TITLE
UIStackView

### ISSUE THREAD

**Issue by fabb** [bpoplauschi/BPForms#27]
Do you think it would be technically possible to rewrite BPForms to use an UIStackView internally? I think about trying to do it due to some issues with dynamic height and having several model objects to be displayed in one row.

**Comment by bpoplauschi** [comment]
I think that `UIStackView` is definitely a good option for this. The only limitation here (and I mean for `UIStackView` in general) is the fact it's only available in iOS9. Of course, we could use something like https://github.com/oarrabi/OAStackView for earlier, but still this is always an issue with early adoption of a new class.

**Comment by fabb** [comment]
Thanks for your feedback. There might be issues with multiline labels, I need to investigate that.
